services:
  int-db:
    image: mongo:latest
    container_name: int-db-news
    ports:
      - "27018:27017"
    volumes:
      - int-db-data:/data/db
    networks:
      - int-network
    restart: always

volumes:
  int-db-data:

networks:
  int-network:
    driver: bridge